name: Feature
description: 새로운 기능 개발을 위한 이슈 작성
labels: [feat]
body:
  - type: input
    id: title
    attributes:
      label: 기능 요약
      description: 어떤 기능을 추가하나요?
      placeholder: "예: 커뮤니티 게시판 작성 기능"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 상세 설명
      description: 기능을 구체적으로 설명해주세요.
      placeholder: "어떤 문제를 해결하는지, 어떤 동작을 기대하는지"
      value: "/branch-name 기능명"
    validations:
      required: true

